# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configurar.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_configurarWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(707, 370)
        self.btCancelar = QtWidgets.QPushButton(Dialog)
        self.btCancelar.setGeometry(QtCore.QRect(580, 330, 101, 31))
        self.btCancelar.setObjectName("btCancelar")
        self.lbRolarCima_2 = QtWidgets.QLabel(Dialog)
        self.lbRolarCima_2.setGeometry(QtCore.QRect(10, 190, 271, 16))
        self.lbRolarCima_2.setObjectName("lbRolarCima_2")
        self.lbTeclaAtalho = QtWidgets.QLabel(Dialog)
        self.lbTeclaAtalho.setGeometry(QtCore.QRect(10, 280, 271, 16))
        self.lbTeclaAtalho.setObjectName("lbTeclaAtalho")
        self.cbCliqueSimples = QtWidgets.QComboBox(Dialog)
        self.cbCliqueSimples.setGeometry(QtCore.QRect(290, 90, 391, 23))
        self.cbCliqueSimples.setObjectName("cbCliqueSimples")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(406, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.cbRolarCima = QtWidgets.QComboBox(Dialog)
        self.cbRolarCima.setGeometry(QtCore.QRect(290, 150, 391, 23))
        self.cbRolarCima.setEditable(False)
        self.cbRolarCima.setObjectName("cbRolarCima")
        self.cbRolarBaixo = QtWidgets.QComboBox(Dialog)
        self.cbRolarBaixo.setGeometry(QtCore.QRect(290, 180, 391, 23))
        self.cbRolarBaixo.setObjectName("cbRolarBaixo")
        self.lbClique_Simples = QtWidgets.QLabel(Dialog)
        self.lbClique_Simples.setGeometry(QtCore.QRect(10, 100, 271, 16))
        self.lbClique_Simples.setObjectName("lbClique_Simples")
        self.lbRolarCima = QtWidgets.QLabel(Dialog)
        self.lbRolarCima.setGeometry(QtCore.QRect(10, 160, 271, 16))
        self.lbRolarCima.setObjectName("lbRolarCima")
        self.lbNenhumaAcao = QtWidgets.QLabel(Dialog)
        self.lbNenhumaAcao.setGeometry(QtCore.QRect(10, 220, 271, 16))
        self.lbNenhumaAcao.setObjectName("lbNenhumaAcao")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(100, 60, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cbTeclaAtalho = QtWidgets.QComboBox(Dialog)
        self.cbTeclaAtalho.setGeometry(QtCore.QRect(290, 270, 391, 23))
        self.cbTeclaAtalho.setObjectName("cbTeclaAtalho")
        self.cbNenhumaAcao = QtWidgets.QComboBox(Dialog)
        self.cbNenhumaAcao.setGeometry(QtCore.QRect(290, 210, 391, 23))
        self.cbNenhumaAcao.setObjectName("cbNenhumaAcao")
        self.btSalvar = QtWidgets.QPushButton(Dialog)
        self.btSalvar.setGeometry(QtCore.QRect(460, 330, 101, 31))
        self.btSalvar.setObjectName("btSalvar")
        self.lbCliqueDuplo = QtWidgets.QLabel(Dialog)
        self.lbCliqueDuplo.setGeometry(QtCore.QRect(10, 130, 271, 16))
        self.lbCliqueDuplo.setObjectName("lbCliqueDuplo")
        self.cbCliqueInverso = QtWidgets.QComboBox(Dialog)
        self.cbCliqueInverso.setGeometry(QtCore.QRect(290, 240, 391, 23))
        self.cbCliqueInverso.setObjectName("cbCliqueInverso")
        self.lbCliqueInverso = QtWidgets.QLabel(Dialog)
        self.lbCliqueInverso.setGeometry(QtCore.QRect(10, 250, 271, 16))
        self.lbCliqueInverso.setObjectName("lbCliqueInverso")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cbCliqueDuplo = QtWidgets.QComboBox(Dialog)
        self.cbCliqueDuplo.setGeometry(QtCore.QRect(290, 120, 391, 23))
        self.cbCliqueDuplo.setObjectName("cbCliqueDuplo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btCancelar.setText(_translate("Dialog", "Cancelar"))
        self.lbRolarCima_2.setText(_translate("Dialog", "Rolar Página para Baixo:"))
        self.lbTeclaAtalho.setText(_translate("Dialog", "Tecla Atalho:"))
        self.label_11.setText(_translate("Dialog", "Expressões:"))
        self.lbClique_Simples.setText(_translate("Dialog", "Clique simples:"))
        self.lbRolarCima.setText(_translate("Dialog", "Rolar Página para Cima:"))
        self.lbNenhumaAcao.setText(_translate("Dialog", "Nenhuma Ação:"))
        self.label_10.setText(_translate("Dialog", "Comandos:"))
        self.btSalvar.setText(_translate("Dialog", "Salvar"))
        self.lbCliqueDuplo.setText(_translate("Dialog", "Clique Duplo:"))
        self.lbCliqueInverso.setText(_translate("Dialog", "Clique Botão Inverso:"))
        self.label.setText(_translate("Dialog", "Configuração de Comandos do Mouse Expression"))

